apiVersion: v1
kind: Service
metadata:
  name: oss-deps-explorer
spec:
  type: {{ .Values.service.type }}
  selector:
    app: oss-deps-explorer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
